### ISSUE TITLE
Beware when using PkgTemplates

### ISSUE THREAD

**Issue by gdalle** [mmcmanus1/HashBlotto.jl#1]
When you generate the file structure on your computer using PkgTemplates.jl, you might get an error trying to push it because the repo is not empty. In that case, the right way would be to merge changes beforehand, and the wrong way (which also works) is to just do a force push: https://stackoverflow.com/questions/5509543/how-do-i-properly-force-a-git-push

**Comment by mmcmanus1** [comment]
Yep! thanks
