### ISSUE TITLE
Ignore `docs/build/` for real

### ISSUE THREAD

**Issue by gdalle** [mmcmanus1/HashBlotto.jl#4]
https://github.com/mmcmanus1/HashBlotto.jl/blob/7d629ded147f02d7ef63fabea604640404dde890/.gitignore#L4

My best guess is, the `docs/build/` subfolder existed before you added this to `.gitignore`. It contains lots of heavy HTML pages with frequent updates, so what you want to do is remove them from your `main` branch and leave it to CI to push those to the `gh-pages` branch for website generation. This should do the trick: https://stackoverflow.com/questions/19663093/apply-gitignore-on-an-existing-repository-already-tracking-large-number-of-file

**Comment by mmcmanus1** [comment]
Thanks so much! That seemed to do the trick
