### ISSUE TITLE
Make printing optional / use logging instead

### ISSUE THREAD

**Issue by gdalle** [mmcmanus1/HashBlotto.jl#6]
https://github.com/mmcmanus1/HashBlotto.jl/blob/7d629ded147f02d7ef63fabea604640404dde890/src/greed_test.jl#L19

Some users don't want their code to print messages, or they might want to log stuff into a txt file instead. You can make it optional with a kwarg or use https://docs.julialang.org/en/v1/stdlib/Logging/

**Comment by mmcmanus1** [comment]
Thanks!!
